import type { Product } from "../state/types";

/** Twelve pieces with real-world dimensions (metres) and messy, plausible
 *  prices. Names are house-brand style, not "Generic Sofa". */
export const CATALOG: Product[] = [
  {
    id: "sofa-halden",
    name: "Halden 3-seater",
    kind: "sofa",
    category: "seating",
    dims: { w: 2.18, d: 0.94, h: 0.84 },
    price: 1840,
    wallHugging: true,
    clearance: { front: 0.75 },
    variants: [
      { id: "oat", name: "Oat weave", color: "#cdbfa6", finish: "fabric" },
      { id: "slate", name: "Slate wool", color: "#5c626a", finish: "fabric" },
      { id: "cognac", name: "Cognac leather", color: "#8a4f34", finish: "leather" },
    ],
  },
  {
    id: "chair-perch",
    name: "Perch lounge chair",
    kind: "armchair",
    category: "seating",
    dims: { w: 0.82, d: 0.86, h: 0.78 },
    price: 620,
    wallHugging: false,
    clearance: { front: 0.5 },
    variants: [
      { id: "moss", name: "Moss velvet", color: "#5a6b4d", finish: "fabric" },
      { id: "ecru", name: "Ecru bouclé", color: "#ddd3c1", finish: "fabric" },
      { id: "rust", name: "Rust linen", color: "#a5623f", finish: "fabric" },
    ],
  },
  {
    id: "chair-hallam",
    name: "Hallam dining chair",
    kind: "chair",
    category: "seating",
    dims: { w: 0.46, d: 0.52, h: 0.82 },
    price: 145,
    wallHugging: false,
    clearance: { front: 0.45, back: 0.3 },
    variants: [
      { id: "oak", name: "Oak", color: "#c69f6d", finish: "wood" },
      { id: "ash", name: "Black ash", color: "#2f2d2b", finish: "wood" },
      { id: "walnut", name: "Walnut", color: "#6b4632", finish: "wood" },
    ],
  },
  {
    id: "table-versa",
    name: "Versa dining table",
    kind: "table",
    category: "tables",
    dims: { w: 1.6, d: 0.9, h: 0.74 },
    price: 980,
    wallHugging: false,
    clearance: { sides: 0.9 },
    variants: [
      { id: "oak", name: "Oak", color: "#c69f6d", finish: "wood" },
      { id: "walnut", name: "Walnut", color: "#6b4632", finish: "wood" },
    ],
  },
  {
    id: "table-milo",
    name: "Milo coffee table",
    kind: "coffeeTable",
    category: "tables",
    dims: { w: 1.1, d: 0.6, h: 0.4 },
    price: 340,
    wallHugging: false,
    clearance: { front: 0.4 },
    variants: [
      { id: "oak", name: "Oak", color: "#c69f6d", finish: "wood" },
      { id: "black", name: "Blackened oak", color: "#2b2926", finish: "wood" },
      { id: "travertine", name: "Travertine", color: "#d8cdb8", finish: "ceramic" },
    ],
  },
  {
    id: "table-nook",
    name: "Nook side table",
    kind: "sideTable",
    category: "tables",
    dims: { w: 0.44, d: 0.44, h: 0.55 },
    price: 120,
    wallHugging: false,
    clearance: {},
    variants: [
      { id: "oak", name: "Oak", color: "#c69f6d", finish: "wood" },
      { id: "black", name: "Black steel", color: "#26241f", finish: "metal" },
    ],
  },
  {
    id: "bed-lindqvist",
    name: "Lindqvist queen bed",
    kind: "bed",
    category: "sleeping",
    dims: { w: 1.6, d: 2.12, h: 1.0 },
    price: 1290,
    wallHugging: true,
    clearance: { sides: 0.6 },
    variants: [
      { id: "grey", name: "Grey linen", color: "#9a9791", finish: "fabric" },
      { id: "oat", name: "Oat linen", color: "#cabfa8", finish: "fabric" },
      { id: "charcoal", name: "Charcoal linen", color: "#43413d", finish: "fabric" },
    ],
  },
  {
    id: "shelf-stak",
    name: "Stak bookshelf",
    kind: "shelf",
    category: "storage",
    dims: { w: 0.9, d: 0.32, h: 1.86 },
    price: 470,
    wallHugging: true,
    clearance: { front: 0.75 },
    variants: [
      { id: "oak", name: "Oak", color: "#c69f6d", finish: "wood" },
      { id: "white", name: "White oak", color: "#e4dccb", finish: "wood" },
      { id: "black", name: "Black", color: "#26241f", finish: "wood" },
    ],
  },
  {
    id: "screen-fen",
    name: "Fen media unit",
    kind: "screen",
    category: "storage",
    dims: { w: 1.8, d: 0.4, h: 0.52 },
    price: 560,
    wallHugging: true,
    clearance: { front: 2.4 },
    variants: [
      { id: "oak", name: "Oak", color: "#c69f6d", finish: "wood" },
      { id: "black", name: "Black", color: "#26241f", finish: "wood" },
    ],
  },
  {
    id: "lamp-arc",
    name: "Arc floor lamp",
    kind: "lamp",
    category: "lighting",
    dims: { w: 0.4, d: 0.4, h: 1.62 },
    price: 210,
    wallHugging: false,
    clearance: {},
    variants: [
      { id: "brass", name: "Brass", color: "#b08a4a", finish: "metal" },
      { id: "black", name: "Matte black", color: "#26241f", finish: "metal" },
      { id: "nickel", name: "Brushed nickel", color: "#a9aab0", finish: "metal" },
    ],
  },
  {
    id: "rug-dune",
    name: "Dune area rug",
    kind: "rug",
    category: "decor",
    dims: { w: 2.4, d: 1.7, h: 0.02 },
    price: 380,
    wallHugging: false,
    clearance: {},
    variants: [
      { id: "sand", name: "Sand", color: "#cbbda1", finish: "woven" },
      { id: "clay", name: "Clay", color: "#b07a5c", finish: "woven" },
      { id: "ash", name: "Ash", color: "#8f8c85", finish: "woven" },
    ],
  },
  {
    id: "plant-fig",
    name: "Fiddle-leaf fig",
    kind: "plant",
    category: "decor",
    dims: { w: 0.7, d: 0.7, h: 1.7 },
    price: 95,
    wallHugging: false,
    clearance: {},
    variants: [
      { id: "terracotta", name: "Terracotta pot", color: "#b5623c", finish: "ceramic" },
      { id: "white", name: "White pot", color: "#e7e2d7", finish: "ceramic" },
      { id: "black", name: "Black pot", color: "#26241f", finish: "ceramic" },
    ],
  },
];

export const CATALOG_BY_ID = new Map(CATALOG.map((p) => [p.id, p]));

export function getProduct(id: string): Product | undefined {
  return CATALOG_BY_ID.get(id);
}
